# Generated by Django 4.1.2 on 2022-10-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
