# Generated by Django 4.1.2 on 2022-10-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimiento',
            new_name='fecha_creacion',
        ),
    ]
